Detail
GSG-CF05/FoodApp-team15 pull request #7
Opened 2022-02-07 11:15 UTC by MohamedSbaih

Add the first section

2022-02-07 11:43 UTC, MostafaBalousha123 approved these changes

2022-02-07 11:51 UTC, Mo3en-ps approved these changes

2022-02-07 11:57 UTC, sara219 commented on details/details.html
> +    <link rel="stylesheet" href="style/style.css" />
fix the link of the style file 
```suggestion
    <link rel="stylesheet" href="./details.css" />
```

2022-02-07 12:29 UTC, sara219 requested changes
to merge this pull request you should complete the whole page 
you did a great thing by pushing it section by section, but it's not ready to review yet till you're done with the page

2022-02-07 23:37 UTC, MohamedSbaih reviewed
Modified

2022-02-07 23:37 UTC, MohamedSbaih commented on details/details.html
> +    <link rel="stylesheet" href="style/style.css" />
Modified

2022-02-08 15:12 UTC, techhana2014 approved these changes

2022-02-08 17:40 UTC, sara219 submitted a review, later dismissed

2022-02-09 11:20 UTC, Mo3en-ps approved these changes

2022-02-09 11:25 UTC, MostafaBalousha123 approved these changes

2022-02-09 11:25 UTC, sara219 approved these changes

2022-02-09 11:29 UTC, merged